### PR TITLE
modify MPM2-generator

### PR DESCRIPTION
**Pull request by kerschke**
I just added a modified version of the mpm2-generator, which allows to further specify the peaks into

1. spheres
2. rotated ellipses
3. non-rotated ellipses.

Actually the python code already allowed that, but the interface had to be modified accordingly. Maybe, this modified version is useful for your package as well - otherwise just ignore this PR :

### CODE REVIEW

**Comment by kerschke** [comment]
I just further modified the modified mpm2 generator:
- `makeModifiedMPM2` now allows to create unimodal problems
- `makeModifiedMPM2` it stores the information regarding the local and global optima
- initialized a getter function `getLocalOptimum` for the local optima

**Comment by kerschke** [comment]
Could you re-start the test on AppVeyor? It crashed and I guess it's rather a bug from AppVeyor rather than a bug in the code (at least it worked on my machine as well as on Travis)..

**Comment by jakobbossek** [comment]
Thx! I glimpsed at the code and I wonder why we even need the `makeModfiedMPM2Function` generator? The difference to the existing `makeMPM2Function` generator are basically the `rotated` and `peakShape` arguments. I guess setting these to `false` and `sphere` respectively results in the currently implemented version? Why not simply modify/adapt `makeMPM2Function`?

Moreover, in smoof I do not use CaMeL-case for variables. Hence, it should be `peak.shape` instead of `peakShape`.

**Comment by jakobbossek** [comment]
The `rotated` argument is relevant only if `peak.shape != "sphere`, right? Could you add a note for this in the description of the `rotated` argument?

**Comment by kerschke** [comment]
I just didn't know, whether you still want to keep your current version of the MPM2 generator or not. That's why I added the additional version.

**Comment by kerschke** [comment]
Alright, I integrated all the modifications into the "original" mpm2 generator and removed my previous modified version.

**Pull request merged**
