### PR TITLE
Add DTLZ1 - 7

### PR DESCRIPTION
**Pull request by lkreft**
- functions are double checked against [jMetal](https://github.com/jMetal/jMetal) and [deap](https://github.com/DEAP/deap)
- C++ code is 6 to 10 times faster than R, but not yet documented
- formatting of documentation via \deqn and \eqn doesn't to work inside the HTML-based help of RStudio (not only a problem of DTLZ, but also of ZDT and others), any ideas?

### CODE REVIEW

**Comment by jakobbossek** [comment]
Hi, good work, but I will not merging at the moment. Travis CI build [fails](https://travis-ci.org/jakobbossek/smoof/builds/89062581) due to a lot of LaTeX errors when building the pdf manual. Fix that stuff and we can merge :+1:

**Comment by jakobbossek** [comment]
Indeed math formulas in the HTML help files do not work. Similar behaviour in the console of course. I have no solution for that and as far as I know there is no solution at the moment. The R Core team should definitely have a look at the [mathjax project](https://www.mathjax.org/).

**Comment by jakobbossek** [comment]
ping

**Comment by lkreft** [comment]
Oh well, this happens when you just read your email notifications. Did not see your first comment. I will have a look at it!

**Comment by jakobbossek** [comment]
I would like to update to v1.1 on CRAN soon. Would be awesome if you could spent some time on it in the next days :+1:

**Comment by lkreft** [comment]
Spent some time on it now, would you mind to write the tests on your own? There is a university project which requires my attention :wink:

The documentation of the DTLZ problems is a little different from the others, as the problem definition is not part of the description but now down in the details due to formatting issues (line breaks and stuff). Additionally, I noticed that deqn accepts two arguments (`\deqn{}{}`), where the second one is what to write into the HTML help. I added this to the DTLZ files, but it may be a good idea to review the other functions as well.

**Comment by jakobbossek** [comment]
Ok, great. No problem. Thanks for the effort.

**Pull request merged**
