### PR TITLE
Add Hartmann 6D function

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by jakobbossek** [comment]
The \bmatrix environment cannot be used. Unfortunately R allows only base math as indicated in the "writing R extensions": **Note that only basic LaTeX can be used, there being no provision to specify LaTeX style files such as the AMS extensions.**
This sucks. However, simply replace bmatrix with matrix 👍

**Comment by jakobbossek** [comment]
There are still some latex problems left. Misplaced alignment tag character. Please fix.

**Comment by jakob-r** [comment]
I hope now it works. Somehow the local check did not signal that.

**Comment by jakob-r** [comment]
Honestly. I don't have a clue what is failing in latex :frowning:

**Comment by jakobbossek** [comment]
ok. I figured out, that even the `\matrix` environment needs amsmath which we simply cannot make use of. Either try to build a matrix by hand (maybe with `\array`; no idea if this is vanilla latex) or get rid of the matrix stuff and reference a website or a paper for that.

**Comment by jakob-r** [comment]
Now it works. But you can't blame me for the coverage decrease, or can you?

**Comment by jakobbossek** [comment]
> Now it works.

👍 

> But you can't blame me for the coverage decrease, or can you?

No, this is no problem.

Going to have a look at the PR in detail in a free minute.


No. This is no problem.

**Comment by jakobbossek** [comment]
Some points still need to be fixed:
1) Rename the generator to `makeHartmann6Function` since there are [multiple other Hartmann function](http://www-optima.amp.i.kyoto-u.ac.jp/member/student/hedar/Hedar_files/TestGO_files/Page1488.htm)
2) Add whitespaces to `rowSums(A[,1:6]*(x.mat-P)^2)`, i.e., `rowSums(A[, 1:6] * (x.mat - P)^2)`
3) There are bad copy and paste errors in the last 4 lines of the Hartmann `attr(makeBirdFunction, "name") = c("Hartmann")`

**Comment by jakob-r** [comment]
It's a bit confusing that the Hartmann3 function uses another matrix then the Hartmann4 and 6 which use the same. I don't know how to deal with it the best.

**Comment by jakobbossek** [comment]
I see 
```
checking PDF version of manual without hyperrefs or index ... ERRORchecking for code/documentation mismatches ... WARNING
Functions or methods with usage in documentation object 'makeHartmannFunction' but not in code:
  makeHartmannFunction
```
on travis. Travis is furthermore still complaining abound the matrix environment. This is because there is and Rd file for makeHartmannFunction. This function does not exist anymore.

**Comment by jakobbossek** [comment]
> It's a bit confusing that the Hartmann3 function uses another matrix then the Hartmann4 and 6
> which use the same. I don't know how to deal with it the best.

Deal in which context? 

You could also write a single function `makeHartmannFunction(dimensions)` where dimensions is limited to {3, 4, 6}. Maybe this is a better design choice? What do you think?

**Comment by jakobbossek** [comment]
You should add the `multimodal` tag to the Hartmann functions.

**Comment by jakob-r** [comment]
4 and 6 are based on the same matrices (A,P) with 4 using just the first 4 of 6 rows. 3 however uses completely different matrices. Also the optima differ for each dimension.

**Comment by jakobbossek** [comment]
> 4 and 6 are based on the same matrices (A,P) with 4 using just the first 4 of 6 rows. 3 however 
> uses completely different matrices. Also the optima differ for each dimension.

Yes, right. I think we could nevertheless save some lines of redundant code.
Your decision 👍

**Comment by jakobbossek** [comment]
There are still `\begin{matrix} ... \end{matrix}` environments. I guess you forgot to rebuild the docs.

**Comment by jakobbossek** [comment]
ping

**Comment by berndbischl** [comment]
can we merge that in pretty quickly? what is left to do?
i would also like to have hartmann3

**Comment by berndbischl** [comment]
ok looking at the code i guess we have hartmann3

**Comment by berndbischl** [comment]
property "differentiable" is at least missing

**Comment by jakob-r** [comment]
The problem remaining now is that the smoof tests expect functions with the scalable tag to run with two dimensions as well.

**Comment by jakobbossek** [comment]
For the moment add the generator to the second argument of `setdiff` in line 8 of `test_soofuns.R`.

**Comment by jakob-r** [comment]
You should also have writing rights in this fork. It's probably faster than fixing it this way.

**Comment by jakobbossek** [comment]
Merged. @jakob-r Thanks for the contribution.

**Comment by berndbischl** [comment]
thx guys

**Pull request merged**
